language: go

go:
 - "1.10"

before_script:
 - go get github.com/mattn/goveralls

script:
 - $GOPATH/bin/goveralls -service=travis-ci
 - go test github.com/nyaruka/goflow/... -bench=. -benchmem

after_success:
 - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
