language: go

go:
 - "1.11"

before_install:
 - sudo apt-get install -y pandoc

script:
 - go test -p=1 -coverprofile=coverage.text -covermode=atomic github.com/nyaruka/goflow/...

after_success:
 - bash <(curl -s https://codecov.io/bash)
 - rm coverage.text
 - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
