language: go

go:
 - "1.10"

services:
 - redis-server

before_script:
 - go get github.com/mattn/goveralls

script:
 - $HOME/gopath/bin/goveralls -service=travis-ci
 - go test $(go list ./... | grep -v /vendor/) -cover
 - go test $(go list ./... | grep -v /vendor/) -cover -bench=. -benchmem

after_success:
 - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash