language: go

go:
 - "1.10"

before_script:
 - go get github.com/mattn/goveralls

script:
 - go test -covermode=count -coverprofile=profile.cov github.com/nyaruka/goflow/...
 - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
 - go test github.com/nyaruka/goflow/... -bench=. -benchmem

after_success:
 - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
