#-------------------------------------------------------------------------------------
# Flowserver settings can be set in four different ways, in order of preference, last
# being highest priority:
#
# 1) Flowserver defaults
# 2) Config file options as defined below
# 3) Env variable, which are prefixed with FLOWSERVER_, ex: export FLOWSERVER_PORT=8000
# 4) Command line options, ex: flowserver -port 8000
#
#-------------------------------------------------------------------------------------

# Which port to listen on
port = 8800

# Log level, one of: panic, fatal, error, warn, info, debug
log_level = "info"
