#-------------------------------------------------------------------------------------
# Flowserver settings can be set in four different ways, in order of preference, last
# being highest priority:
#
# 1) Flowserver defaults
# 2) Config file options as defined below
# 3) Env variable, which are prefixed with FLOWSERVER_, ex: export FLOWSERVER_PORT=8000
# 4) Command line options, ex: flowserver -port 8000
#
#-------------------------------------------------------------------------------------

# Which port to listen on
Port = 8080

# Directory where static content is served from
Static = ""

# Asset cache settings - how many items it can hold and how many to prune when it reaches that size
AssetCacheSize = 1000
AssetCachePrune = 100
AssetServerToken = "missing_auth_token"